import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { inflateSync } from "node:zlib";
import { describe, expect, it } from "vitest";

/**
 * The app's mark is one drawing with several copies, and the way it goes wrong
 * is quiet: someone redraws `icon.svg`, regenerates the rasters, and the copies
 * nobody regenerated keep the old logo. That is the bug this file exists to
 * catch, so it asserts the copies agree — the paths, the stroke, the opacity —
 * rather than trusting that they do.
 *
 * `uiGuide.test.ts` set the precedent for reading source files off disk; this
 * rides the same `bun run test` step, so drift fails on every PR without a
 * workflow change.
 */
const ROOT = fileURLToPath(new URL("../../", import.meta.url));
const read = (relative: string) => readFileSync(`${ROOT}${relative}`, "utf8");

/** The mark's geometry. One source, asserted against every copy. */
const WARP = "M6.5 5.5c0 6.5 5.5 6.5 5.5 13";
const WEFT = "M12 5.5c0 6.5 5.5 6.5 5.5 13";
const HEM = "M6.5 18.5h11";
const STROKE = 1.9;
const HEM_OPACITY = 0.55;
const ROUND_RADIUS = 5.4;

/** Every file that draws the mark, so a new copy has to be added here. */
const COPIES = [
  { file: "src-tauri/icons/icon.svg", shape: "square" },
  { file: "src-tauri/icons/icon-round.svg", shape: "round" },
  { file: "site/src/app/icon.svg", shape: "round" },
] as const;

describe("the app mark", () => {
  it.each(COPIES)("$file draws the same three threads", ({ file }) => {
    const svg = read(file);
    expect(svg, `${file} is missing the warp thread`).toContain(WARP);
    expect(svg, `${file} is missing the weft thread`).toContain(WEFT);
    expect(svg, `${file} is missing the hem`).toContain(HEM);
    expect(svg, `${file} changed the stroke width`).toMatch(
      new RegExp(`stroke-width=["']${STROKE}["']`),
    );
    expect(svg, `${file} changed the hem's opacity`).toMatch(
      new RegExp(`opacity=["']${HEM_OPACITY}["']`),
    );
    expect(
      svg.includes(`stroke-linecap="round"`) || svg.includes("stroke-linecap='round'"),
      `${file} stopped rounding its line caps`,
    ).toBe(true);
  });

  it("keeps the OS icons full-bleed and the browser icons rounded", () => {
    // Not an accident: a shell supplies its own corner radius, a browser tab
    // does not. Asserted so "both shapes" stays deliberate.
    const os = read("src-tauri/icons/icon.svg");
    expect(os, "the OS icon must stay square").not.toMatch(/<rect[^>]*\brx=/);

    for (const file of ["src-tauri/icons/icon-round.svg", "site/src/app/icon.svg"]) {
      expect(read(file), `${file} must carry the window radius`).toContain(
        `rx="${ROUND_RADIUS}"`,
      );
    }
  });

  it("keeps index.html's favicon in step with the mark", () => {
    const html = read("index.html");
    const href = /<link\s+rel="icon"\s+href="([^"]+)"/.exec(html);
    expect(href, "index.html has no favicon link").not.toBeNull();

    const decoded = decodeURIComponent(href![1]);
    expect(decoded, "the favicon is no longer a data URI of the mark").toContain(
      WARP,
    );
    expect(decoded).toContain(WEFT);
    expect(decoded).toContain(HEM);
    // Generated by `bun run icons`, so a hand-edit here shows up as drift.
    expect(decoded, "the favicon lost the rounded tile").toContain(
      `rx='${ROUND_RADIUS}'`,
    );
  });

  it("draws the React copies with the same geometry", () => {
    // Three hand-written React copies remain (the app, Setup, the site). They
    // are the ones a regeneration cannot reach, so they are checked here.
    for (const file of [
      "src/components/icons.tsx",
      "setup/src/App.tsx",
      "site/src/components/loom-mark.tsx",
    ]) {
      const source = read(file);
      expect(source, `${file} changed the warp thread`).toContain(WARP);
      expect(source, `${file} changed the weft thread`).toContain(WEFT);
      expect(source, `${file} changed the hem`).toContain(HEM);
    }
  });

  it("ships the same .ico to the app and to the installer", () => {
    // The app's icon lands on the installed exe; Setup's on the installer and
    // on every shortcut it writes. Different bytes means a shortcut that draws
    // a different logo from the app it launches.
    const app = readFileSync(`${ROOT}src-tauri/icons/icon.ico`);
    const setup = readFileSync(`${ROOT}setup/src-tauri/icons/icon.ico`);
    expect(
      setup.equals(app),
      "setup/src-tauri/icons/icon.ico differs from the app's — run `bun run icons`",
    ).toBe(true);
  });

  it("keeps every shipped raster monochrome", () => {
    // The regression this catches: the mark replaced by coloured artwork, or a
    // tinted PNG exported over the top of it.
    const rasters = [
      "128x128.png",
      "128x128@2x.png",
      "32x32.png",
      "64x64.png",
      "StoreLogo.png",
      "Square30x30Logo.png",
      "Square44x44Logo.png",
      "Square71x71Logo.png",
      "Square89x89Logo.png",
      "Square107x107Logo.png",
      "Square142x142Logo.png",
      "Square150x150Logo.png",
      "Square284x284Logo.png",
      "Square310x310Logo.png",
    ];

    for (const name of rasters) {
      const png = readFileSync(`${ROOT}src-tauri/icons/${name}`);
      const { worst } = channelSpread(png);
      // Black, white, and the greys between. A stray hue is the tell.
      expect(worst, `${name} carries colour (spread ${worst})`).toBeLessThanOrEqual(8);
    }
  });

  it("packs the same mark into every image of the .ico", () => {
    const ico = readFileSync(`${ROOT}src-tauri/icons/icon.ico`);
    const images = icoImages(ico);
    expect(images.length, "the .ico has no images").toBeGreaterThan(0);

    for (const image of images) {
      const { worst } = channelSpread(image.png);
      expect(
        worst,
        `the ${image.width}x${image.height} entry carries colour`,
      ).toBeLessThanOrEqual(8);
    }
  });
});

// ---------------------------------------------------------------------------
// A minimal PNG reader, so the colour assertions above need no dependency. Only
// what the check requires: IHDR for the size, then the unfiltered scanlines in
// order to compare each pixel's channels.
// ---------------------------------------------------------------------------
interface Png {
  width: number;
  height: number;
  channels: number;
  pixels: Buffer;
}

function decodePng(buffer: Buffer): Png | null {
  if (buffer.subarray(0, 8).toString("hex") !== "89504e470d0a1a0a") return null;

  const width = buffer.readUInt32BE(16);
  const height = buffer.readUInt32BE(20);
  const depth = buffer.readUInt8(24);
  const colorType = buffer.readUInt8(25);
  if (depth !== 8) return null;

  const channels = { 0: 1, 2: 3, 4: 2, 6: 4 }[colorType];
  if (!channels) return null;

  // Every IDAT chunk, concatenated, is the zlib stream.
  const chunks: Buffer[] = [];
  let offset = 8;
  while (offset + 8 <= buffer.length) {
    const length = buffer.readUInt32BE(offset);
    const type = buffer.subarray(offset + 4, offset + 8).toString("ascii");
    if (type === "IDAT") chunks.push(buffer.subarray(offset + 8, offset + 8 + length));
    offset += 12 + length;
    if (type === "IEND") break;
  }

  const raw = inflateSync(Buffer.concat(chunks));
  const stride = width * channels;
  const pixels = Buffer.alloc(stride * height);
  let previous = Buffer.alloc(stride);
  let position = 0;

  for (let y = 0; y < height; y++) {
    const filter = raw[position++];
    const line = Buffer.from(raw.subarray(position, position + stride));
    position += stride;

    for (let x = 0; x < stride; x++) {
      const a = x >= channels ? line[x - channels] : 0;
      const b = previous[x];
      const c = x >= channels ? previous[x - channels] : 0;
      if (filter === 1) line[x] = (line[x] + a) & 255;
      else if (filter === 2) line[x] = (line[x] + b) & 255;
      else if (filter === 3) line[x] = (line[x] + ((a + b) >> 1)) & 255;
      else if (filter === 4) {
        const p = a + b - c;
        const pa = Math.abs(p - a);
        const pb = Math.abs(p - b);
        const pc = Math.abs(p - c);
        line[x] = (line[x] + (pa <= pb && pa <= pc ? a : pb <= pc ? b : c)) & 255;
      }
    }

    line.copy(pixels, y * stride);
    previous = line;
  }

  return { width, height, channels, pixels };
}

/** The widest gap between a pixel's colour channels, over the whole image. */
function channelSpread(buffer: Buffer): { worst: number } {
  const png = decodePng(buffer);
  if (!png) return { worst: 0 }; // Not a colour PNG: nothing to spread.
  if (png.channels < 3) return { worst: 0 }; // Already greyscale.

  let worst = 0;
  for (let index = 0; index + png.channels <= png.pixels.length; index += png.channels) {
    const r = png.pixels[index];
    const g = png.pixels[index + 1];
    const b = png.pixels[index + 2];
    const spread = Math.max(r, g, b) - Math.min(r, g, b);
    if (spread > worst) worst = spread;
  }
  return { worst };
}

interface IcoImage {
  width: number;
  height: number;
  png: Buffer;
}

/** The PNG-compressed entries of an .ico. Bitmap entries are skipped. */
function icoImages(ico: Buffer): IcoImage[] {
  const count = ico.readUInt16LE(4);
  const images: IcoImage[] = [];
  let offset = 6;

  for (let index = 0; index < count; index++) {
    const width = ico.readUInt8(offset) || 256;
    const height = ico.readUInt8(offset + 1) || 256;
    const size = ico.readUInt32LE(offset + 8);
    const start = ico.readUInt32LE(offset + 12);
    const png = ico.subarray(start, start + size);
    if (png.subarray(0, 8).toString("hex") === "89504e470d0a1a0a") {
      images.push({ width, height, png });
    }
    offset += 16;
  }

  return images;
}
